// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:3.1.0.0
//      SpecFlow Generator Version:3.1.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace ImageRename.Tests.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class ImageGPSFeature : object, Xunit.IClassFixture<ImageGPSFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "ImageGPS.feature"
#line hidden
        
        public ImageGPSFeature(ImageGPSFeature.FixtureData fixtureData, ImageRename_Tests_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-GB"), "ImageGPS", null, ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 3
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Path"});
            table2.AddRow(new string[] {
                        "CheckTheImageHasGPSCoridinates"});
            table2.AddRow(new string[] {
                        "GPSKeywords"});
#line 4
 testRunner.Given("I delete the folders", ((string)(null)), table2, "Given ");
#line hidden
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="CheckTheImageHasGPSCoridinates")]
        [Xunit.TraitAttribute("FeatureTitle", "ImageGPS")]
        [Xunit.TraitAttribute("Description", "CheckTheImageHasGPSCoridinates")]
        public virtual void CheckTheImageHasGPSCoridinates()
        {
            string[] tagsOfScenario = ((string[])(null));
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("CheckTheImageHasGPSCoridinates", null, ((string[])(null)));
#line 9
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 3
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                            "SourceFolder",
                            "SourceFile",
                            "DestinationFolder",
                            "DestinationFile"});
                table3.AddRow(new string[] {
                            "JPG",
                            "GPS.jpg",
                            "CheckTheImageHasGPSCoridinates",
                            "GPS.jpg"});
                table3.AddRow(new string[] {
                            "JPG",
                            "Good.jpg",
                            "CheckTheImageHasGPSCoridinates",
                            "Good.jpg"});
                table3.AddRow(new string[] {
                            "JPG",
                            "Bad.jpg",
                            "CheckTheImageHasGPSCoridinates",
                            "Bad.jpg"});
#line 10
 testRunner.Given("I copy the following files", ((string)(null)), table3, "Given ");
#line hidden
                TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                            "TestFolder",
                            "TestFile",
                            "Longitude",
                            "Latitude",
                            "DegreesLongitude",
                            "DegreesLatitude",
                            "ImageCreatedOriginal",
                            "ImageTaken",
                            "GPSImageTaken",
                            "DestinationFileName",
                            "KeyWords"});
                table4.AddRow(new string[] {
                            "CheckTheImageHasGPSCoridinates",
                            "GPS.jpg",
                            "5.00°21.04\'0.00\" W",
                            "36.00°7.08\'0.00\" N",
                            "-5.35",
                            "36.11666666666667",
                            "27 Jan 2020 12:50:42",
                            "27 Jan 2020 11:50:41",
                            "27 Jan 2020 11:50:41",
                            "20200127_115041",
                            "Gibraltar;"});
                table4.AddRow(new string[] {
                            "CheckTheImageHasGPSCoridinates",
                            "Good.jpg",
                            "",
                            "",
                            "",
                            "",
                            "10 Mar 2018 11:53:53",
                            "10 Mar 2018 11:53:53",
                            "",
                            "20180310_115353",
                            ""});
                table4.AddRow(new string[] {
                            "CheckTheImageHasGPSCoridinates",
                            "Bad.jpg",
                            "",
                            "",
                            "",
                            "",
                            "",
                            "",
                            "",
                            "",
                            ""});
#line 15
 testRunner.Then("the following files have the values in the ImageFile object", ((string)(null)), table4, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="GPSKeywords")]
        [Xunit.TraitAttribute("FeatureTitle", "ImageGPS")]
        [Xunit.TraitAttribute("Description", "GPSKeywords")]
        public virtual void GPSKeywords()
        {
            string[] tagsOfScenario = ((string[])(null));
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("GPSKeywords", null, ((string[])(null)));
#line 21
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 3
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                            "Source",
                            "TestFolder",
                            "TestFile",
                            "Longitude",
                            "Latitude",
                            "ImageCreatedOriginal",
                            "GPSImageTaken",
                            "Keywords"});
                table5.AddRow(new string[] {
                            "JPG\\Good.jpg",
                            "GPSKeywords",
                            "aaaa.jpg",
                            "5.00°21.04\'0.00\" W",
                            "36.00°7.08\'0.00\" N",
                            "27 Jan 2020 09:50:42",
                            "27 Jan 2020 11:50:41",
                            ""});
                table5.AddRow(new string[] {
                            "JPG\\Good.jpg",
                            "GPSKeywords",
                            "bbbb.jpg",
                            "5.00°21.04\'0.00\" W",
                            "36.00°7.08\'0.00\" N",
                            "27 Jan 2020 10:50:42",
                            "27 Jan 2020 12:50:41",
                            "BlueBell; Tinkerbell;"});
                table5.AddRow(new string[] {
                            "JPG\\Good.jpg",
                            "GPSKeywords",
                            "cccc.jpg",
                            "4.00°8.00\'37.392\" W",
                            "50.00°7.21\'56.066\" N",
                            "27 Jan 2019 11:45:42",
                            "27 Jan 2019 13:45:42",
                            ""});
                table5.AddRow(new string[] {
                            "JPG\\Good.jpg",
                            "GPSKeywords",
                            "dddd.jpg",
                            "4.00°8.00\'37.392\" W",
                            "50.00°7.21\'56.066\" N",
                            "27 Jan 2019 12:45:42",
                            "27 Jan 2019 14:45:42",
                            "rain;snow;sun;"});
                table5.AddRow(new string[] {
                            "JPG\\Good.jpg",
                            "GPSKeywords",
                            "eeee.jpg",
                            "",
                            "",
                            "27 Jan 2020 16:50:41",
                            "",
                            ""});
                table5.AddRow(new string[] {
                            "JPG\\Good.jpg",
                            "GPSKeywords",
                            "ffff.jpg",
                            "",
                            "",
                            "27 Jan 2020 17:50:41",
                            "",
                            "rain;snow;sun;"});
                table5.AddRow(new string[] {
                            "JPG\\Good.jpg",
                            "GPSKeywords",
                            "gggg.jpg",
                            "",
                            "",
                            "27 Jan 2020 18:50:41",
                            "",
                            ""});
                table5.AddRow(new string[] {
                            "JPG\\Good.jpg",
                            "GPSKeywords",
                            "hhhh.jpg",
                            "",
                            "",
                            "27 Jan 2020 19:50:41",
                            "",
                            "BlueBell; Tinkerbell;"});
#line 22
 testRunner.Given("I create image objects with the following properties", ((string)(null)), table5, "Given ");
#line hidden
                TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                            "TestFile",
                            "Longitude",
                            "Latitude",
                            "DegreesLongitude",
                            "DegreesLatitude",
                            "ImageCreatedOriginal",
                            "ImageTaken",
                            "GPSImageTaken",
                            "DestinationFileName",
                            "KeyWords"});
                table6.AddRow(new string[] {
                            "aaaa.jpg",
                            "5.00°21.04\'0.00\" W",
                            "36.00°7.08\'0.00\" N",
                            "-5.35",
                            "36.11666666666667",
                            "27 Jan 2020 09:50:42",
                            "27 Jan 2020 09:50:42",
                            "27 Jan 2020 11:50:41",
                            "20200127_095042",
                            "Gibraltar;"});
                table6.AddRow(new string[] {
                            "bbbb.jpg",
                            "5.00°21.04\'0.00\" W",
                            "36.00°7.08\'0.00\" N",
                            "-5.35",
                            "36.11666666666667",
                            "27 Jan 2020 10:50:42",
                            "27 Jan 2020 10:50:42",
                            "27 Jan 2020 12:50:41",
                            "20200127_105042",
                            "BlueBell; Tinkerbell;Gibraltar;"});
                table6.AddRow(new string[] {
                            "cccc.jpg",
                            "4.00°8.00\'37.392\" W",
                            "50.00°7.21\'56.066\" N",
                            "-4.14372",
                            "50.132240555555555",
                            "27 Jan 2019 11:45:42",
                            "27 Jan 2019 11:45:42",
                            "27 Jan 2019 01:45:42",
                            "20190127_114542",
                            ""});
                table6.AddRow(new string[] {
                            "dddd.jpg",
                            "4.00°8.00\'37.392\" W",
                            "50.00°7.21\'56.066\" N",
                            "-4.14372",
                            "50.132240555555555",
                            "27 Jan 2019 12:45:42",
                            "27 Jan 2019 12:45:42",
                            "27 Jan 2019 02:45:42",
                            "20190127_124542",
                            "rain;snow;sun;"});
                table6.AddRow(new string[] {
                            "eeee.jpg",
                            "",
                            "",
                            "",
                            "",
                            "27 Jan 2020 04:50:41",
                            "27 Jan 2020 04:50:41",
                            "",
                            "20200127_165041",
                            ""});
                table6.AddRow(new string[] {
                            "ffff.jpg",
                            "",
                            "",
                            "",
                            "",
                            "27 Jan 2020 05:50:41",
                            "27 Jan 2020 05:50:41",
                            "",
                            "20200127_175041",
                            "rain;snow;sun;"});
                table6.AddRow(new string[] {
                            "gggg.jpg",
                            "",
                            "",
                            "",
                            "",
                            "27 Jan 2020 06:50:41",
                            "27 Jan 2020 06:50:41",
                            "",
                            "20200127_185041",
                            ""});
                table6.AddRow(new string[] {
                            "hhhh.jpg",
                            "",
                            "",
                            "",
                            "",
                            "27 Jan 2020 07:50:41",
                            "27 Jan 2020 07:50:41",
                            "",
                            "20200127_195041",
                            "BlueBell; Tinkerbell;"});
#line 32
 testRunner.Then("the image object list has following values", ((string)(null)), table6, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.1.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                ImageGPSFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                ImageGPSFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
