// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:3.1.0.0
//      SpecFlow Generator Version:3.1.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace ImageRename.Tests.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class ImageGPSFeature : object, Xunit.IClassFixture<ImageGPSFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "ImageGPS.feature"
#line hidden
        
        public ImageGPSFeature(ImageGPSFeature.FixtureData fixtureData, ImageRename_Tests_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-GB"), "ImageGPS", null, ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 3
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Path"});
            table2.AddRow(new string[] {
                        "CheckTheImageHasGPSCoridinates"});
            table2.AddRow(new string[] {
                        "GPSKeywords"});
#line 4
 testRunner.Given("I delete the folders", ((string)(null)), table2, "Given ");
#line hidden
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="CheckTheImageHasGPSCoridinates")]
        [Xunit.TraitAttribute("FeatureTitle", "ImageGPS")]
        [Xunit.TraitAttribute("Description", "CheckTheImageHasGPSCoridinates")]
        public virtual void CheckTheImageHasGPSCoridinates()
        {
            string[] tagsOfScenario = ((string[])(null));
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("CheckTheImageHasGPSCoridinates", null, ((string[])(null)));
#line 9
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 3
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                            "Folder",
                            "FileName",
                            "Keywords",
                            "ImageCreatedOriginal",
                            "ImageTaken",
                            "GPSImageTaken",
                            "Longitude",
                            "Latitude"});
                table3.AddRow(new string[] {
                            "CheckTheImageHasGPSCoridinates\\Internet",
                            "aa01.jpg",
                            "",
                            "27 Jan 2020 12:50:42",
                            "27 Jan 2020 12:50:42",
                            "",
                            "",
                            ""});
                table3.AddRow(new string[] {
                            "CheckTheImageHasGPSCoridinates\\Internet",
                            "aa02.jpg",
                            "Green;Blue;",
                            "27 Jan 2020 12:50:42",
                            "27 Jan 2020 12:50:42",
                            "",
                            "",
                            ""});
                table3.AddRow(new string[] {
                            "CheckTheImageHasGPSCoridinates\\Internet",
                            "aa03.jpg",
                            "Gibraltar;",
                            "27 Jan 2020 12:50:42",
                            "27 Jan 2020 12:50:42",
                            "",
                            "",
                            ""});
                table3.AddRow(new string[] {
                            "CheckTheImageHasGPSCoridinates\\Internet",
                            "aa04.jpg",
                            "Gibraltar;Europe;",
                            "27 Jan 2020 12:50:42",
                            "27 Jan 2020 12:50:42",
                            "",
                            "",
                            ""});
                table3.AddRow(new string[] {
                            "CheckTheImageHasGPSCoridinates\\Internet",
                            "aa05.jpg",
                            "Gibraltar;",
                            "27 Jan 2020 12:50:42",
                            "27 Jan 2020 12:50:42",
                            "",
                            "",
                            ""});
                table3.AddRow(new string[] {
                            "CheckTheImageHasGPSCoridinates\\Internet",
                            "aa06.jpg",
                            "Europe;",
                            "27 Jan 2020 12:50:42",
                            "27 Jan 2020 12:50:42",
                            "",
                            "",
                            ""});
                table3.AddRow(new string[] {
                            "CheckTheImageHasGPSCoridinates\\Internet",
                            "bb01.jpg",
                            "",
                            "27 Jan 2020 12:50:42",
                            "27 Jan 2020 12:50:42",
                            "27 Jan 2020 12:50:42",
                            "5.00°21.04\'0.00\" W",
                            "36.00°7.08\'0.00\" N"});
                table3.AddRow(new string[] {
                            "CheckTheImageHasGPSCoridinates\\Internet",
                            "bb02.jpg",
                            "Green;Blue;",
                            "27 Jan 2020 12:50:42",
                            "27 Jan 2020 12:50:42",
                            "27 Jan 2020 12:50:42",
                            "5.00°21.04\'0.00\" W",
                            "36.00°7.08\'0.00\" N"});
                table3.AddRow(new string[] {
                            "CheckTheImageHasGPSCoridinates\\Internet",
                            "bb03.jpg",
                            "Gibraltar;",
                            "27 Jan 2020 12:50:42",
                            "27 Jan 2020 12:50:42",
                            "27 Jan 2020 12:50:42",
                            "5.00°21.04\'0.00\" W",
                            "36.00°7.08\'0.00\" N"});
                table3.AddRow(new string[] {
                            "CheckTheImageHasGPSCoridinates\\Internet",
                            "bb04.jpg",
                            "Gibraltar;Europe;",
                            "27 Jan 2020 12:50:42",
                            "27 Jan 2020 12:50:42",
                            "27 Jan 2020 12:50:42",
                            "5.00°21.04\'0.00\" W",
                            "36.00°7.08\'0.00\" N"});
                table3.AddRow(new string[] {
                            "CheckTheImageHasGPSCoridinates\\Internet",
                            "bb05.jpg",
                            "Europe;",
                            "27 Jan 2020 12:50:42",
                            "27 Jan 2020 12:50:42",
                            "27 Jan 2020 12:50:42",
                            "5.00°21.04\'0.00\" W",
                            "36.00°7.08\'0.00\" N"});
                table3.AddRow(new string[] {
                            "CheckTheImageHasGPSCoridinates\\Internet",
                            "cc01.jpg",
                            "",
                            "27 Jan 2020 12:50:42",
                            "27 Jan 2020 12:50:42",
                            "27 Jan 2020 14:50:42",
                            "5.00°21.04\'0.00\" W",
                            "36.00°7.08\'0.00\" N"});
                table3.AddRow(new string[] {
                            "CheckTheImageHasGPSCoridinates\\Internet",
                            "cc02.jpg",
                            "Green;Blue;",
                            "27 Jan 2020 12:50:42",
                            "27 Jan 2020 12:50:42",
                            "27 Jan 2020 15:50:42",
                            "5.00°21.04\'0.00\" W",
                            "36.00°7.08\'0.00\" N"});
                table3.AddRow(new string[] {
                            "CheckTheImageHasGPSCoridinates\\Internet",
                            "cc03.jpg",
                            "Gibraltar;",
                            "27 Jan 2020 12:50:42",
                            "27 Jan 2020 12:50:42",
                            "27 Jan 2020 16:50:42",
                            "5.00°21.04\'0.00\" W",
                            "36.00°7.08\'0.00\" N"});
                table3.AddRow(new string[] {
                            "CheckTheImageHasGPSCoridinates\\Internet",
                            "cc04.jpg",
                            "Gibraltar;Europe;",
                            "27 Jan 2020 12:50:42",
                            "27 Jan 2020 12:50:42",
                            "27 Jan 2020 17:50:42",
                            "5.00°21.04\'0.00\" W",
                            "36.00°7.08\'0.00\" N"});
                table3.AddRow(new string[] {
                            "CheckTheImageHasGPSCoridinates\\Internet",
                            "cc05.jpg",
                            "Europe;",
                            "27 Jan 2020 12:50:42",
                            "27 Jan 2020 12:50:42",
                            "27 Jan 2020 18:50:42",
                            "5.00°21.04\'0.00\" W",
                            "36.00°7.08\'0.00\" N"});
                table3.AddRow(new string[] {
                            "CheckTheImageHasGPSCoridinates\\NoInternet",
                            "aa01.jpg",
                            "",
                            "27 Jan 2020 12:50:42",
                            "27 Jan 2020 12:50:42",
                            "",
                            "",
                            ""});
                table3.AddRow(new string[] {
                            "CheckTheImageHasGPSCoridinates\\NoInternet",
                            "aa02.jpg",
                            "Green;Blue;",
                            "27 Jan 2020 12:50:42",
                            "27 Jan 2020 12:50:42",
                            "",
                            "",
                            ""});
                table3.AddRow(new string[] {
                            "CheckTheImageHasGPSCoridinates\\NoInternet",
                            "aa03.jpg",
                            "Gibraltar;",
                            "27 Jan 2020 12:50:42",
                            "27 Jan 2020 12:50:42",
                            "",
                            "",
                            ""});
                table3.AddRow(new string[] {
                            "CheckTheImageHasGPSCoridinates\\NoInternet",
                            "aa04.jpg",
                            "Gibraltar;Europe;",
                            "27 Jan 2020 12:50:42",
                            "27 Jan 2020 12:50:42",
                            "",
                            "",
                            ""});
                table3.AddRow(new string[] {
                            "CheckTheImageHasGPSCoridinates\\NoInternet",
                            "aa05.jpg",
                            "Gibraltar;",
                            "27 Jan 2020 12:50:42",
                            "27 Jan 2020 12:50:42",
                            "",
                            "",
                            ""});
                table3.AddRow(new string[] {
                            "CheckTheImageHasGPSCoridinates\\NoInternet",
                            "aa06.jpg",
                            "Europe;",
                            "27 Jan 2020 12:50:42",
                            "27 Jan 2020 12:50:42",
                            "",
                            "",
                            ""});
                table3.AddRow(new string[] {
                            "CheckTheImageHasGPSCoridinates\\NoInternet",
                            "bb01.jpg",
                            "",
                            "27 Jan 2020 12:50:42",
                            "27 Jan 2020 12:50:42",
                            "27 Jan 2020 12:50:42",
                            "5.00°21.04\'0.00\" W",
                            "36.00°7.08\'0.00\" N"});
                table3.AddRow(new string[] {
                            "CheckTheImageHasGPSCoridinates\\NoInternet",
                            "bb02.jpg",
                            "Green;Blue;",
                            "27 Jan 2020 12:50:42",
                            "27 Jan 2020 12:50:42",
                            "27 Jan 2020 12:50:42",
                            "5.00°21.04\'0.00\" W",
                            "36.00°7.08\'0.00\" N"});
                table3.AddRow(new string[] {
                            "CheckTheImageHasGPSCoridinates\\NoInternet",
                            "bb03.jpg",
                            "Gibraltar;",
                            "27 Jan 2020 12:50:42",
                            "27 Jan 2020 12:50:42",
                            "27 Jan 2020 12:50:42",
                            "5.00°21.04\'0.00\" W",
                            "36.00°7.08\'0.00\" N"});
                table3.AddRow(new string[] {
                            "CheckTheImageHasGPSCoridinates\\NoInternet",
                            "bb04.jpg",
                            "Gibraltar;Europe;",
                            "27 Jan 2020 12:50:42",
                            "27 Jan 2020 12:50:42",
                            "27 Jan 2020 12:50:42",
                            "5.00°21.04\'0.00\" W",
                            "36.00°7.08\'0.00\" N"});
                table3.AddRow(new string[] {
                            "CheckTheImageHasGPSCoridinates\\NoInternet",
                            "bb05.jpg",
                            "Europe;",
                            "27 Jan 2020 12:50:42",
                            "27 Jan 2020 12:50:42",
                            "27 Jan 2020 12:50:42",
                            "5.00°21.04\'0.00\" W",
                            "36.00°7.08\'0.00\" N"});
                table3.AddRow(new string[] {
                            "CheckTheImageHasGPSCoridinates\\NoInternet",
                            "cc01.jpg",
                            "",
                            "27 Jan 2020 12:50:42",
                            "27 Jan 2020 12:50:42",
                            "27 Jan 2020 14:50:42",
                            "5.00°21.04\'0.00\" W",
                            "36.00°7.08\'0.00\" N"});
                table3.AddRow(new string[] {
                            "CheckTheImageHasGPSCoridinates\\NoInternet",
                            "cc02.jpg",
                            "Green;Blue;",
                            "27 Jan 2020 12:50:42",
                            "27 Jan 2020 12:50:42",
                            "27 Jan 2020 15:50:42",
                            "5.00°21.04\'0.00\" W",
                            "36.00°7.08\'0.00\" N"});
                table3.AddRow(new string[] {
                            "CheckTheImageHasGPSCoridinates\\NoInternet",
                            "cc03.jpg",
                            "Gibraltar;",
                            "27 Jan 2020 12:50:42",
                            "27 Jan 2020 12:50:42",
                            "27 Jan 2020 16:50:42",
                            "5.00°21.04\'0.00\" W",
                            "36.00°7.08\'0.00\" N"});
                table3.AddRow(new string[] {
                            "CheckTheImageHasGPSCoridinates\\NoInternet",
                            "cc04.jpg",
                            "Gibraltar;Europe;",
                            "27 Jan 2020 12:50:42",
                            "27 Jan 2020 12:50:42",
                            "27 Jan 2020 17:50:42",
                            "5.00°21.04\'0.00\" W",
                            "36.00°7.08\'0.00\" N"});
                table3.AddRow(new string[] {
                            "CheckTheImageHasGPSCoridinates\\NoInternet",
                            "cc05.jpg",
                            "Europe;",
                            "27 Jan 2020 12:50:42",
                            "27 Jan 2020 12:50:42",
                            "27 Jan 2020 18:50:42",
                            "5.00°21.04\'0.00\" W",
                            "36.00°7.08\'0.00\" N"});
#line 10
 testRunner.Given("I create the JPEG files", ((string)(null)), table3, "Given ");
#line hidden
                TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                            "TestFolder",
                            "TestFile",
                            "HasInternet",
                            "Longitude",
                            "Latitude",
                            "DegreesLongitude",
                            "DegreesLatitude",
                            "ImageCreatedOriginal",
                            "ImageTaken",
                            "GPSImageTaken",
                            "DestinationFileName",
                            "KeyWords"});
                table4.AddRow(new string[] {
                            "CheckTheImageHasGPSCoridinates\\Internet",
                            "aa01.jpg",
                            "True",
                            "",
                            "",
                            "",
                            "",
                            "27 Jan 2020 12:50:42",
                            "27 Jan 2020 12:50:42",
                            "",
                            "20200127_125042",
                            ""});
                table4.AddRow(new string[] {
                            "CheckTheImageHasGPSCoridinates\\Internet",
                            "aa02.jpg",
                            "True",
                            "",
                            "",
                            "",
                            "",
                            "27 Jan 2020 12:50:42",
                            "27 Jan 2020 12:50:42",
                            "",
                            "20200127_125042",
                            "Green;Blue;"});
                table4.AddRow(new string[] {
                            "CheckTheImageHasGPSCoridinates\\Internet",
                            "aa04.jpg",
                            "True",
                            "",
                            "",
                            "",
                            "",
                            "27 Jan 2020 12:50:42",
                            "27 Jan 2020 12:50:42",
                            "",
                            "20200127_125042",
                            "Gibraltar;Europe;"});
                table4.AddRow(new string[] {
                            "CheckTheImageHasGPSCoridinates\\Internet",
                            "aa04.jpg",
                            "True",
                            "",
                            "",
                            "",
                            "",
                            "27 Jan 2020 12:50:42",
                            "27 Jan 2020 12:50:42",
                            "",
                            "20200127_125042",
                            "Gibraltar;Europe;"});
                table4.AddRow(new string[] {
                            "CheckTheImageHasGPSCoridinates\\Internet",
                            "aa05.jpg",
                            "True",
                            "",
                            "",
                            "",
                            "",
                            "27 Jan 2020 12:50:42",
                            "27 Jan 2020 12:50:42",
                            "",
                            "20200127_125042",
                            "Gibraltar;"});
                table4.AddRow(new string[] {
                            "CheckTheImageHasGPSCoridinates\\Internet",
                            "aa06.jpg",
                            "True",
                            "",
                            "",
                            "",
                            "",
                            "27 Jan 2020 12:50:42",
                            "27 Jan 2020 12:50:42",
                            "",
                            "20200127_125042",
                            "Europe;"});
                table4.AddRow(new string[] {
                            "CheckTheImageHasGPSCoridinates\\Internet",
                            "bb01.jpg",
                            "True",
                            "5.00°21.04\'0.00\" W",
                            "36.00°7.08\'0.00\" N",
                            "-5.35",
                            "36.11666666666667",
                            "27 Jan 2020 12:50:42",
                            "27 Jan 2020 12:50:42",
                            "27 Jan 2020 12:50:42",
                            "20200127_125042",
                            "Gibraltar;Europe;"});
                table4.AddRow(new string[] {
                            "CheckTheImageHasGPSCoridinates\\Internet",
                            "bb02.jpg",
                            "True",
                            "5.00°21.04\'0.00\" W",
                            "36.00°7.08\'0.00\" N",
                            "-5.35",
                            "36.11666666666667",
                            "27 Jan 2020 12:50:42",
                            "27 Jan 2020 12:50:42",
                            "27 Jan 2020 12:50:42",
                            "20200127_125042",
                            "Green;Blue;Gibraltar;Europe;"});
                table4.AddRow(new string[] {
                            "CheckTheImageHasGPSCoridinates\\Internet",
                            "bb03.jpg",
                            "True",
                            "5.00°21.04\'0.00\" W",
                            "36.00°7.08\'0.00\" N",
                            "-5.35",
                            "36.11666666666667",
                            "27 Jan 2020 12:50:42",
                            "27 Jan 2020 12:50:42",
                            "27 Jan 2020 12:50:42",
                            "20200127_125042",
                            "Gibraltar;Europe;"});
                table4.AddRow(new string[] {
                            "CheckTheImageHasGPSCoridinates\\Internet",
                            "bb04.jpg",
                            "True",
                            "5.00°21.04\'0.00\" W",
                            "36.00°7.08\'0.00\" N",
                            "-5.35",
                            "36.11666666666667",
                            "27 Jan 2020 12:50:42",
                            "27 Jan 2020 12:50:42",
                            "27 Jan 2020 12:50:42",
                            "20200127_125042",
                            "Gibraltar;Europe;"});
                table4.AddRow(new string[] {
                            "CheckTheImageHasGPSCoridinates\\Internet",
                            "bb05.jpg",
                            "True",
                            "5.00°21.04\'0.00\" W",
                            "36.00°7.08\'0.00\" N",
                            "-5.35",
                            "36.11666666666667",
                            "27 Jan 2020 12:50:42",
                            "27 Jan 2020 12:50:42",
                            "27 Jan 2020 12:50:42",
                            "20200127_125042",
                            "Europe;Gibraltar;"});
                table4.AddRow(new string[] {
                            "CheckTheImageHasGPSCoridinates\\Internet",
                            "cc01.jpg",
                            "True",
                            "5.00°21.04\'0.00\" W",
                            "36.00°7.08\'0.00\" N",
                            "-5.35",
                            "36.11666666666667",
                            "27 Jan 2020 12:50:42",
                            "27 Jan 2020 14:50:42",
                            "27 Jan 2020 14:50:42",
                            "20200127_145042",
                            "Gibraltar;Europe;"});
                table4.AddRow(new string[] {
                            "CheckTheImageHasGPSCoridinates\\Internet",
                            "cc02.jpg",
                            "True",
                            "5.00°21.04\'0.00\" W",
                            "36.00°7.08\'0.00\" N",
                            "-5.35",
                            "36.11666666666667",
                            "27 Jan 2020 12:50:42",
                            "27 Jan 2020 15:50:42",
                            "27 Jan 2020 15:50:42",
                            "20200127_155042",
                            "Green;Blue;Gibraltar;Europe;"});
                table4.AddRow(new string[] {
                            "CheckTheImageHasGPSCoridinates\\Internet",
                            "cc03.jpg",
                            "True",
                            "5.00°21.04\'0.00\" W",
                            "36.00°7.08\'0.00\" N",
                            "-5.35",
                            "36.11666666666667",
                            "27 Jan 2020 12:50:42",
                            "27 Jan 2020 16:50:42",
                            "27 Jan 2020 16:50:42",
                            "20200127_165042",
                            "Gibraltar;Europe;"});
                table4.AddRow(new string[] {
                            "CheckTheImageHasGPSCoridinates\\Internet",
                            "cc04.jpg",
                            "True",
                            "5.00°21.04\'0.00\" W",
                            "36.00°7.08\'0.00\" N",
                            "-5.35",
                            "36.11666666666667",
                            "27 Jan 2020 12:50:42",
                            "27 Jan 2020 17:50:42",
                            "27 Jan 2020 17:50:42",
                            "20200127_175042",
                            "Gibraltar;Europe;"});
                table4.AddRow(new string[] {
                            "CheckTheImageHasGPSCoridinates\\Internet",
                            "cc05.jpg",
                            "True",
                            "5.00°21.04\'0.00\" W",
                            "36.00°7.08\'0.00\" N",
                            "-5.35",
                            "36.11666666666667",
                            "27 Jan 2020 12:50:42",
                            "27 Jan 2020 18:50:42",
                            "27 Jan 2020 18:50:42",
                            "20200127_185042",
                            "Europe;Gibraltar;"});
                table4.AddRow(new string[] {
                            "CheckTheImageHasGPSCoridinates\\NoInternet",
                            "aa01.jpg",
                            "True",
                            "",
                            "",
                            "",
                            "",
                            "27 Jan 2020 12:50:42",
                            "27 Jan 2020 12:50:42",
                            "",
                            "20200127_125042",
                            ""});
                table4.AddRow(new string[] {
                            "CheckTheImageHasGPSCoridinates\\NoInternet",
                            "aa02.jpg",
                            "True",
                            "",
                            "",
                            "",
                            "",
                            "27 Jan 2020 12:50:42",
                            "27 Jan 2020 12:50:42",
                            "",
                            "20200127_125042",
                            "Green;Blue;"});
                table4.AddRow(new string[] {
                            "CheckTheImageHasGPSCoridinates\\NoInternet",
                            "aa04.jpg",
                            "True",
                            "",
                            "",
                            "",
                            "",
                            "27 Jan 2020 12:50:42",
                            "27 Jan 2020 12:50:42",
                            "",
                            "20200127_125042",
                            "Gibraltar;Europe;"});
                table4.AddRow(new string[] {
                            "CheckTheImageHasGPSCoridinates\\NoInternet",
                            "aa04.jpg",
                            "True",
                            "",
                            "",
                            "",
                            "",
                            "27 Jan 2020 12:50:42",
                            "27 Jan 2020 12:50:42",
                            "",
                            "20200127_125042",
                            "Gibraltar;Europe;"});
                table4.AddRow(new string[] {
                            "CheckTheImageHasGPSCoridinates\\NoInternet",
                            "aa05.jpg",
                            "True",
                            "",
                            "",
                            "",
                            "",
                            "27 Jan 2020 12:50:42",
                            "27 Jan 2020 12:50:42",
                            "",
                            "20200127_125042",
                            "Gibraltar;"});
                table4.AddRow(new string[] {
                            "CheckTheImageHasGPSCoridinates\\NoInternet",
                            "aa06.jpg",
                            "True",
                            "",
                            "",
                            "",
                            "",
                            "27 Jan 2020 12:50:42",
                            "27 Jan 2020 12:50:42",
                            "",
                            "20200127_125042",
                            "Europe;"});
                table4.AddRow(new string[] {
                            "CheckTheImageHasGPSCoridinates\\NoInternet",
                            "bb01.jpg",
                            "False",
                            "5.00°21.04\'0.00\" W",
                            "36.00°7.08\'0.00\" N",
                            "-5.35",
                            "36.11666666666667",
                            "27 Jan 2020 12:50:42",
                            "27 Jan 2020 12:50:42",
                            "27 Jan 2020 12:50:42",
                            "20200127_125042",
                            ""});
                table4.AddRow(new string[] {
                            "CheckTheImageHasGPSCoridinates\\NoInternet",
                            "bb02.jpg",
                            "False",
                            "5.00°21.04\'0.00\" W",
                            "36.00°7.08\'0.00\" N",
                            "-5.35",
                            "36.11666666666667",
                            "27 Jan 2020 12:50:42",
                            "27 Jan 2020 12:50:42",
                            "27 Jan 2020 12:50:42",
                            "20200127_125042",
                            "Green;Blue;"});
                table4.AddRow(new string[] {
                            "CheckTheImageHasGPSCoridinates\\NoInternet",
                            "bb03.jpg",
                            "False",
                            "5.00°21.04\'0.00\" W",
                            "36.00°7.08\'0.00\" N",
                            "-5.35",
                            "36.11666666666667",
                            "27 Jan 2020 12:50:42",
                            "27 Jan 2020 12:50:42",
                            "27 Jan 2020 12:50:42",
                            "20200127_125042",
                            "Gibraltar;"});
                table4.AddRow(new string[] {
                            "CheckTheImageHasGPSCoridinates\\NoInternet",
                            "bb04.jpg",
                            "False",
                            "5.00°21.04\'0.00\" W",
                            "36.00°7.08\'0.00\" N",
                            "-5.35",
                            "36.11666666666667",
                            "27 Jan 2020 12:50:42",
                            "27 Jan 2020 12:50:42",
                            "27 Jan 2020 12:50:42",
                            "20200127_125042",
                            "Gibraltar;Europe;"});
                table4.AddRow(new string[] {
                            "CheckTheImageHasGPSCoridinates\\NoInternet",
                            "bb05.jpg",
                            "False",
                            "5.00°21.04\'0.00\" W",
                            "36.00°7.08\'0.00\" N",
                            "-5.35",
                            "36.11666666666667",
                            "27 Jan 2020 12:50:42",
                            "27 Jan 2020 12:50:42",
                            "27 Jan 2020 12:50:42",
                            "20200127_125042",
                            "Europe;"});
                table4.AddRow(new string[] {
                            "CheckTheImageHasGPSCoridinates\\NoInternet",
                            "cc01.jpg",
                            "False",
                            "5.00°21.04\'0.00\" W",
                            "36.00°7.08\'0.00\" N",
                            "-5.35",
                            "36.11666666666667",
                            "27 Jan 2020 12:50:42",
                            "27 Jan 2020 14:50:42",
                            "27 Jan 2020 14:50:42",
                            "20200127_145042",
                            ""});
                table4.AddRow(new string[] {
                            "CheckTheImageHasGPSCoridinates\\NoInternet",
                            "cc02.jpg",
                            "False",
                            "5.00°21.04\'0.00\" W",
                            "36.00°7.08\'0.00\" N",
                            "-5.35",
                            "36.11666666666667",
                            "27 Jan 2020 12:50:42",
                            "27 Jan 2020 15:50:42",
                            "27 Jan 2020 15:50:42",
                            "20200127_155042",
                            "Green;Blue;"});
                table4.AddRow(new string[] {
                            "CheckTheImageHasGPSCoridinates\\NoInternet",
                            "cc03.jpg",
                            "False",
                            "5.00°21.04\'0.00\" W",
                            "36.00°7.08\'0.00\" N",
                            "-5.35",
                            "36.11666666666667",
                            "27 Jan 2020 12:50:42",
                            "27 Jan 2020 16:50:42",
                            "27 Jan 2020 16:50:42",
                            "20200127_165042",
                            "Gibraltar;"});
                table4.AddRow(new string[] {
                            "CheckTheImageHasGPSCoridinates\\NoInternet",
                            "cc04.jpg",
                            "False",
                            "5.00°21.04\'0.00\" W",
                            "36.00°7.08\'0.00\" N",
                            "-5.35",
                            "36.11666666666667",
                            "27 Jan 2020 12:50:42",
                            "27 Jan 2020 17:50:42",
                            "27 Jan 2020 17:50:42",
                            "20200127_175042",
                            "Gibraltar;Europe;"});
                table4.AddRow(new string[] {
                            "CheckTheImageHasGPSCoridinates\\NoInternet",
                            "cc05.jpg",
                            "False",
                            "5.00°21.04\'0.00\" W",
                            "36.00°7.08\'0.00\" N",
                            "-5.35",
                            "36.11666666666667",
                            "27 Jan 2020 12:50:42",
                            "27 Jan 2020 18:50:42",
                            "27 Jan 2020 18:50:42",
                            "20200127_185042",
                            "Europe;"});
#line 46
 testRunner.Then("the following files have the values in the ImageFile object", ((string)(null)), table4, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="GPSKeywords")]
        [Xunit.TraitAttribute("FeatureTitle", "ImageGPS")]
        [Xunit.TraitAttribute("Description", "GPSKeywords")]
        public virtual void GPSKeywords()
        {
            string[] tagsOfScenario = ((string[])(null));
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("GPSKeywords", null, ((string[])(null)));
#line 82
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 3
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                            "Source",
                            "TestFolder",
                            "HasInternet",
                            "TestFile",
                            "Longitude",
                            "Latitude",
                            "ImageCreatedOriginal",
                            "ImageTaken",
                            "GPSImageTaken",
                            "Keywords"});
                table5.AddRow(new string[] {
                            "JPG\\Good.jpg",
                            "GPSKeywords",
                            "true",
                            "aaaa.jpg",
                            "5.00°21.04\'0.00\" W",
                            "36.00°7.08\'0.00\" N",
                            "27 Jan 2020 09:50:42",
                            "27 Jan 2020 09:50:42",
                            "27 Jan 2020 11:50:41",
                            ""});
                table5.AddRow(new string[] {
                            "JPG\\Good.jpg",
                            "GPSKeywords",
                            "true",
                            "bbbb.jpg",
                            "5.00°21.04\'0.00\" W",
                            "36.00°7.08\'0.00\" N",
                            "27 Jan 2020 10:50:42",
                            "27 Jan 2020 10:50:42",
                            "27 Jan 2020 12:50:41",
                            "BlueBell;Tinkerbell;"});
                table5.AddRow(new string[] {
                            "JPG\\Good.jpg",
                            "GPSKeywords",
                            "true",
                            "cccc.jpg",
                            "4.00°8.00\'37.392\" W",
                            "50.00°7.21\'56.066\" N",
                            "27 Jan 2019 11:45:42",
                            "27 Jan 2019 11:45:42",
                            "27 Jan 2019 13:45:42",
                            ""});
                table5.AddRow(new string[] {
                            "JPG\\Good.jpg",
                            "GPSKeywords",
                            "true",
                            "dddd.jpg",
                            "4.00°8.00\'37.392\" W",
                            "50.00°7.21\'56.066\" N",
                            "27 Jan 2019 12:45:42",
                            "27 Jan 2019 12:45:42",
                            "27 Jan 2019 14:45:42",
                            "rain;snow;sun;"});
                table5.AddRow(new string[] {
                            "JPG\\Good.jpg",
                            "GPSKeywords",
                            "true",
                            "eeee.jpg",
                            "",
                            "",
                            "27 Jan 2020 16:50:41",
                            "27 Jan 2020 16:50:41",
                            "",
                            ""});
                table5.AddRow(new string[] {
                            "JPG\\Good.jpg",
                            "GPSKeywords",
                            "true",
                            "ffff.jpg",
                            "",
                            "",
                            "27 Jan 2020 17:50:41",
                            "27 Jan 2020 17:50:41",
                            "",
                            "rain;snow;sun;"});
                table5.AddRow(new string[] {
                            "JPG\\Good.jpg",
                            "GPSKeywords",
                            "true",
                            "gggg.jpg",
                            "",
                            "",
                            "27 Jan 2020 18:50:41",
                            "27 Jan 2020 18:50:41",
                            "",
                            ""});
                table5.AddRow(new string[] {
                            "JPG\\Good.jpg",
                            "GPSKeywords",
                            "true",
                            "hhhh.jpg",
                            "",
                            "",
                            "27 Jan 2020 19:50:41",
                            "27 Jan 2020 19:50:41",
                            "",
                            "BlueBell;Tinkerbell;"});
                table5.AddRow(new string[] {
                            "JPG\\Good.jpg",
                            "GPSKeywords",
                            "false",
                            "iiii.jpg",
                            "5.00°21.04\'0.00\" W",
                            "36.00°7.08\'0.00\" N",
                            "27 Jan 2020 09:50:42",
                            "27 Jan 2020 09:50:42",
                            "27 Jan 2020 11:50:41",
                            ""});
                table5.AddRow(new string[] {
                            "JPG\\Good.jpg",
                            "GPSKeywords",
                            "false",
                            "jjjj.jpg",
                            "5.00°21.04\'0.00\" W",
                            "36.00°7.08\'0.00\" N",
                            "27 Jan 2020 10:50:42",
                            "27 Jan 2020 10:50:42",
                            "27 Jan 2020 12:50:41",
                            "BlueBell;Tinkerbell;"});
                table5.AddRow(new string[] {
                            "JPG\\Good.jpg",
                            "GPSKeywords",
                            "false",
                            "kkkk.jpg",
                            "4.00°8.00\'37.392\" W",
                            "50.00°7.21\'56.066\" N",
                            "27 Jan 2019 11:45:42",
                            "27 Jan 2019 11:45:42",
                            "27 Jan 2019 13:45:42",
                            ""});
                table5.AddRow(new string[] {
                            "JPG\\Good.jpg",
                            "GPSKeywords",
                            "false",
                            "llll.jpg",
                            "4.00°8.00\'37.392\" W",
                            "50.00°7.21\'56.066\" N",
                            "27 Jan 2019 12:45:42",
                            "27 Jan 2019 12:45:42",
                            "27 Jan 2019 14:45:42",
                            "rain;snow;sun;"});
                table5.AddRow(new string[] {
                            "JPG\\Good.jpg",
                            "GPSKeywords",
                            "false",
                            "mmmm.jpg",
                            "",
                            "",
                            "27 Jan 2020 16:50:41",
                            "27 Jan 2020 16:50:41",
                            "",
                            ""});
                table5.AddRow(new string[] {
                            "JPG\\Good.jpg",
                            "GPSKeywords",
                            "false",
                            "nnnn.jpg",
                            "",
                            "",
                            "27 Jan 2020 17:50:41",
                            "27 Jan 2020 17:50:41",
                            "",
                            "rain;snow;sun;"});
                table5.AddRow(new string[] {
                            "JPG\\Good.jpg",
                            "GPSKeywords",
                            "false",
                            "oooo.jpg",
                            "",
                            "",
                            "27 Jan 2020 18:50:41",
                            "27 Jan 2020 18:50:41",
                            "",
                            ""});
                table5.AddRow(new string[] {
                            "JPG\\Good.jpg",
                            "GPSKeywords",
                            "false",
                            "pppp.jpg",
                            "",
                            "",
                            "27 Jan 2020 19:50:41",
                            "27 Jan 2020 19:50:41",
                            "",
                            "BlueBell;Tinkerbell;"});
                table5.AddRow(new string[] {
                            "JPG\\Good.jpg",
                            "GPSKeywords",
                            "true",
                            "qqqq.jpg",
                            "5.00°21.04\'0.00\" W",
                            "36.00°7.08\'0.00\" N",
                            "27 Jan 2020 09:50:42",
                            "27 Jan 2020 09:50:42",
                            "27 Jan 2020 11:50:41",
                            "Gibraltar;"});
                table5.AddRow(new string[] {
                            "JPG\\Good.jpg",
                            "GPSKeywords",
                            "true",
                            "rrrr.jpg",
                            "5.00°21.04\'0.00\" W",
                            "36.00°7.08\'0.00\" N",
                            "27 Jan 2020 09:50:42",
                            "27 Jan 2020 09:50:42",
                            "27 Jan 2020 11:50:41",
                            "Gibraltar;Europe;"});
                table5.AddRow(new string[] {
                            "JPG\\Good.jpg",
                            "GPSKeywords",
                            "true",
                            "ssss.jpg",
                            "4.00°41.00\'59.279\" W",
                            "51.00°41.00\'39.24\" N",
                            "27 Jan 2020 09:50:42",
                            "27 Jan 2020 09:50:42",
                            "27 Jan 2020 11:50:41",
                            ""});
                table5.AddRow(new string[] {
                            "JPG\\Good.jpg",
                            "GPSKeywords",
                            "true",
                            "tttt.jpg",
                            "12.00°30.00\'21.763\" E",
                            "55.00°52.00\'25.54\" N",
                            "27 Jan 2020 09:50:42",
                            "27 Jan 2020 09:50:42",
                            "27 Jan 2020 11:50:41",
                            ""});
                table5.AddRow(new string[] {
                            "JPG\\Good.jpg",
                            "GPSKeywords",
                            "true",
                            "uuuu.jpg",
                            "6.00°42.00\'37.335\" E",
                            "45.00°48.00\'15.45\" N",
                            "27 Jan 2020 09:50:42",
                            "27 Jan 2020 09:50:42",
                            "27 Jan 2020 11:50:41",
                            ""});
                table5.AddRow(new string[] {
                            "JPG\\Good.jpg",
                            "GPSKeywords",
                            "true",
                            "vvvv.jpg",
                            "9.00°52.00\'4.4\" E",
                            "53.00°33.00\'38.652\" N",
                            "27 Jan 2020 09:50:42",
                            "27 Jan 2020 09:50:42",
                            "27 Jan 2020 11:50:41",
                            ""});
#line 83
 testRunner.Given("I create image objects with the following properties", ((string)(null)), table5, "Given ");
#line hidden
                TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                            "TestFile",
                            "Longitude",
                            "Latitude",
                            "DegreesLongitude",
                            "DegreesLatitude",
                            "ImageCreatedOriginal",
                            "ImageTaken",
                            "GPSImageTaken",
                            "DestinationFileName",
                            "KeyWords"});
                table6.AddRow(new string[] {
                            "aaaa.jpg",
                            "5.00°21.04\'0.00\" W",
                            "36.00°7.08\'0.00\" N",
                            "-5.35",
                            "36.11666666666667",
                            "27 Jan 2020 09:50:42",
                            "27 Jan 2020 09:50:42",
                            "27 Jan 2020 11:50:41",
                            "20200127_115041",
                            "Gibraltar;Europe;"});
                table6.AddRow(new string[] {
                            "bbbb.jpg",
                            "5.00°21.04\'0.00\" W",
                            "36.00°7.08\'0.00\" N",
                            "-5.35",
                            "36.11666666666667",
                            "27 Jan 2020 10:50:42",
                            "27 Jan 2020 10:50:42",
                            "27 Jan 2020 12:50:41",
                            "20200127_125041",
                            "BlueBell;Tinkerbell;Gibraltar;Europe;"});
                table6.AddRow(new string[] {
                            "cccc.jpg",
                            "4.00°8.00\'37.392\" W",
                            "50.00°7.21\'56.066\" N",
                            "-4.14372",
                            "50.132240555555555",
                            "27 Jan 2019 11:45:42",
                            "27 Jan 2019 11:45:42",
                            "27 Jan 2019 13:45:42",
                            "20190127_134542",
                            ""});
                table6.AddRow(new string[] {
                            "dddd.jpg",
                            "4.00°8.00\'37.392\" W",
                            "50.00°7.21\'56.066\" N",
                            "-4.14372",
                            "50.132240555555555",
                            "27 Jan 2019 12:45:42",
                            "27 Jan 2019 12:45:42",
                            "27 Jan 2019 14:45:42",
                            "20190127_144542",
                            "rain;snow;sun;"});
                table6.AddRow(new string[] {
                            "eeee.jpg",
                            "",
                            "",
                            "",
                            "",
                            "27 Jan 2020 16:50:41",
                            "27 Jan 2020 16:50:41",
                            "",
                            "20200127_165041",
                            ""});
                table6.AddRow(new string[] {
                            "ffff.jpg",
                            "",
                            "",
                            "",
                            "",
                            "27 Jan 2020 17:50:41",
                            "27 Jan 2020 17:50:41",
                            "",
                            "20200127_175041",
                            "rain;snow;sun;"});
                table6.AddRow(new string[] {
                            "gggg.jpg",
                            "",
                            "",
                            "",
                            "",
                            "27 Jan 2020 18:50:41",
                            "27 Jan 2020 18:50:41",
                            "",
                            "20200127_185041",
                            ""});
                table6.AddRow(new string[] {
                            "hhhh.jpg",
                            "",
                            "",
                            "",
                            "",
                            "27 Jan 2020 19:50:41",
                            "27 Jan 2020 19:50:41",
                            "",
                            "20200127_195041",
                            "BlueBell;Tinkerbell;"});
                table6.AddRow(new string[] {
                            "iiii.jpg",
                            "5.00°21.04\'0.00\" W",
                            "36.00°7.08\'0.00\" N",
                            "-5.35",
                            "36.11666666666667",
                            "27 Jan 2020 09:50:42",
                            "27 Jan 2020 09:50:42",
                            "27 Jan 2020 11:50:41",
                            "20200127_115041",
                            ""});
                table6.AddRow(new string[] {
                            "jjjj.jpg",
                            "5.00°21.04\'0.00\" W",
                            "36.00°7.08\'0.00\" N",
                            "-5.35",
                            "36.11666666666667",
                            "27 Jan 2020 10:50:42",
                            "27 Jan 2020 10:50:42",
                            "27 Jan 2020 12:50:41",
                            "20200127_125041",
                            "BlueBell;Tinkerbell;"});
                table6.AddRow(new string[] {
                            "kkkk.jpg",
                            "4.00°8.00\'37.392\" W",
                            "50.00°7.21\'56.066\" N",
                            "-4.14372",
                            "50.132240555555555",
                            "27 Jan 2019 11:45:42",
                            "27 Jan 2019 11:45:42",
                            "27 Jan 2019 13:45:42",
                            "20190127_134542",
                            ""});
                table6.AddRow(new string[] {
                            "llll.jpg",
                            "4.00°8.00\'37.392\" W",
                            "50.00°7.21\'56.066\" N",
                            "-4.14372",
                            "50.132240555555555",
                            "27 Jan 2019 12:45:42",
                            "27 Jan 2019 12:45:42",
                            "27 Jan 2019 14:45:42",
                            "20190127_144542",
                            "rain;snow;sun;"});
                table6.AddRow(new string[] {
                            "mmmm.jpg",
                            "",
                            "",
                            "",
                            "",
                            "27 Jan 2020 16:50:41",
                            "27 Jan 2020 16:50:41",
                            "",
                            "20200127_165041",
                            ""});
                table6.AddRow(new string[] {
                            "nnnn.jpg",
                            "",
                            "",
                            "",
                            "",
                            "27 Jan 2020 17:50:41",
                            "27 Jan 2020 17:50:41",
                            "",
                            "20200127_175041",
                            "rain;snow;sun;"});
                table6.AddRow(new string[] {
                            "oooo.jpg",
                            "",
                            "",
                            "",
                            "",
                            "27 Jan 2020 18:50:41",
                            "27 Jan 2020 18:50:41",
                            "",
                            "20200127_185041",
                            ""});
                table6.AddRow(new string[] {
                            "pppp.jpg",
                            "",
                            "",
                            "",
                            "",
                            "27 Jan 2020 19:50:41",
                            "27 Jan 2020 19:50:41",
                            "",
                            "20200127_195041",
                            "BlueBell;Tinkerbell;"});
                table6.AddRow(new string[] {
                            "qqqq.jpg",
                            "5.00°21.04\'0.00\" W",
                            "36.00°7.08\'0.00\" N",
                            "-5.35",
                            "36.11666666666667",
                            "27 Jan 2020 09:50:42",
                            "27 Jan 2020 09:50:42",
                            "27 Jan 2020 11:50:41",
                            "20200127_115041",
                            "Gibraltar;Europe;"});
                table6.AddRow(new string[] {
                            "rrrr.jpg",
                            "5.00°21.04\'0.00\" W",
                            "36.00°7.08\'0.00\" N",
                            "-5.35",
                            "36.11666666666667",
                            "27 Jan 2020 09:50:42",
                            "27 Jan 2020 09:50:42",
                            "27 Jan 2020 11:50:41",
                            "20200127_115041",
                            "Gibraltar;Europe;"});
                table6.AddRow(new string[] {
                            "ssss.jpg",
                            "4.00°41.00\'59.279\" W",
                            "51.00°41.00\'39.24\" N",
                            "-4.699799722222222",
                            "51.69423333333333",
                            "27 Jan 2020 09:50:42",
                            "27 Jan 2020 09:50:42",
                            "27 Jan 2020 11:50:41",
                            "20200127_115041",
                            "United Kingdom;Europe;Wales;Pembrokeshire;"});
                table6.AddRow(new string[] {
                            "tttt.jpg",
                            "12.00°30.00\'21.763\" E",
                            "55.00°52.00\'25.54\" N",
                            "12.506045277777778",
                            "55.873761111111115",
                            "27 Jan 2020 09:50:42",
                            "27 Jan 2020 09:50:42",
                            "27 Jan 2020 11:50:41",
                            "20200127_115041",
                            "Denmark;Europe;Hørsholm;"});
                table6.AddRow(new string[] {
                            "uuuu.jpg",
                            "6.00°42.00\'37.335\" E",
                            "45.00°48.00\'15.45\" N",
                            "6.710370833333333",
                            "45.804291666666664",
                            "27 Jan 2020 09:50:42",
                            "27 Jan 2020 09:50:42",
                            "27 Jan 2020 11:50:41",
                            "20200127_115041",
                            "France;Europe;Les Contamines-Montjoie;Auvergne-Rhone-Alpes;Haute-Savoie;"});
                table6.AddRow(new string[] {
                            "vvvv.jpg",
                            "9.00°52.00\'4.4\" E",
                            "53.00°33.00\'38.652\" N",
                            "9.867888888888888",
                            "53.56073666666666",
                            "27 Jan 2020 09:50:42",
                            "27 Jan 2020 09:50:42",
                            "27 Jan 2020 11:50:41",
                            "20200127_115041",
                            "Germany;Europe;Hamburg;"});
#line 109
 testRunner.Then("the image object list has following values", ((string)(null)), table6, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.1.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                ImageGPSFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                ImageGPSFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
