// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:3.1.0.0
//      SpecFlow Generator Version:3.1.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace ImageRename.Tests.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class ImageGPSFeature : object, Xunit.IClassFixture<ImageGPSFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "ImageGPS.feature"
#line hidden
        
        public ImageGPSFeature(ImageGPSFeature.FixtureData fixtureData, ImageRename_Tests_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-GB"), "ImageGPS", null, ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 3
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Path"});
            table2.AddRow(new string[] {
                        "CheckTheImageHasGPSCoridinates"});
            table2.AddRow(new string[] {
                        "GPSKeywords"});
#line 4
 testRunner.Given("I delete the folders", ((string)(null)), table2, "Given ");
#line hidden
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="CheckTheImageHasGPSCoridinates")]
        [Xunit.TraitAttribute("FeatureTitle", "ImageGPS")]
        [Xunit.TraitAttribute("Description", "CheckTheImageHasGPSCoridinates")]
        public virtual void CheckTheImageHasGPSCoridinates()
        {
            string[] tagsOfScenario = ((string[])(null));
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("CheckTheImageHasGPSCoridinates", null, ((string[])(null)));
#line 9
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 3
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                            "SourceFolder",
                            "SourceFile",
                            "DestinationFolder",
                            "DestinationFile"});
                table3.AddRow(new string[] {
                            "JPG",
                            "GPS.jpg",
                            "CheckTheImageHasGPSCoridinates\\Internet",
                            "GPS.jpg"});
                table3.AddRow(new string[] {
                            "JPG",
                            "GPS.jpg",
                            "CheckTheImageHasGPSCoridinates\\Internet",
                            "GPS2.jpg"});
                table3.AddRow(new string[] {
                            "JPG",
                            "GPS.jpg",
                            "CheckTheImageHasGPSCoridinates\\Internet",
                            "GPS3.jpg"});
                table3.AddRow(new string[] {
                            "JPG",
                            "GPS.jpg",
                            "CheckTheImageHasGPSCoridinates\\Internet",
                            "GPS4.jpg"});
                table3.AddRow(new string[] {
                            "JPG",
                            "Good.jpg",
                            "CheckTheImageHasGPSCoridinates\\Internet",
                            "Good.jpg"});
                table3.AddRow(new string[] {
                            "JPG",
                            "Good.jpg",
                            "CheckTheImageHasGPSCoridinates\\Internet",
                            "Good2.jpg"});
                table3.AddRow(new string[] {
                            "JPG",
                            "Bad.jpg",
                            "CheckTheImageHasGPSCoridinates\\Internet",
                            "Bad.jpg"});
                table3.AddRow(new string[] {
                            "JPG",
                            "GPS.jpg",
                            "CheckTheImageHasGPSCoridinates\\NoInternet",
                            "GPS.jpg"});
                table3.AddRow(new string[] {
                            "JPG",
                            "GPS.jpg",
                            "CheckTheImageHasGPSCoridinates\\NoInternet",
                            "GPS2.jpg"});
                table3.AddRow(new string[] {
                            "JPG",
                            "Good.jpg",
                            "CheckTheImageHasGPSCoridinates\\NoInternet",
                            "Good.jpg"});
                table3.AddRow(new string[] {
                            "JPG",
                            "Good.jpg",
                            "CheckTheImageHasGPSCoridinates\\NoInternet",
                            "Good2.jpg"});
                table3.AddRow(new string[] {
                            "JPG",
                            "Bad.jpg",
                            "CheckTheImageHasGPSCoridinates\\NoInternet",
                            "Bad.jpg"});
#line 10
 testRunner.Given("I copy the following files", ((string)(null)), table3, "Given ");
#line hidden
                TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                            "Filename",
                            "Keywords"});
                table4.AddRow(new string[] {
                            "CheckTheImageHasGPSCoridinates\\Internet\\GPS2.jpg",
                            "Green;Blue;"});
                table4.AddRow(new string[] {
                            "CheckTheImageHasGPSCoridinates\\Internet\\GPS3.jpg",
                            "Gibraltar;"});
                table4.AddRow(new string[] {
                            "CheckTheImageHasGPSCoridinates\\Internet\\GPS4.jpg",
                            "Gibraltar;Europe;"});
                table4.AddRow(new string[] {
                            "CheckTheImageHasGPSCoridinates\\Internet\\Good2.jpg",
                            "Red;Orange;"});
                table4.AddRow(new string[] {
                            "CheckTheImageHasGPSCoridinates\\NoInternet\\GPS2.jpg",
                            "Green;Blue;"});
                table4.AddRow(new string[] {
                            "CheckTheImageHasGPSCoridinates\\NoInternet\\Good2.jpg",
                            "Red;Orange;"});
#line 25
 testRunner.And("I add the keywords to the files", ((string)(null)), table4, "And ");
#line hidden
                TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                            "TestFolder",
                            "TestFile",
                            "HasInternet",
                            "Longitude",
                            "Latitude",
                            "DegreesLongitude",
                            "DegreesLatitude",
                            "ImageCreatedOriginal",
                            "ImageTaken",
                            "GPSImageTaken",
                            "DestinationFileName",
                            "KeyWords"});
                table5.AddRow(new string[] {
                            "CheckTheImageHasGPSCoridinates\\Internet",
                            "GPS.jpg",
                            "true",
                            "5.00°21.04\'0.00\" W",
                            "36.00°7.08\'0.00\" N",
                            "-5.35",
                            "36.11666666666667",
                            "27 Jan 2020 12:50:42",
                            "27 Jan 2020 11:50:41",
                            "27 Jan 2020 11:50:41",
                            "20200127_115041",
                            "Gibraltar;Europe;"});
                table5.AddRow(new string[] {
                            "CheckTheImageHasGPSCoridinates\\Internet",
                            "GPS2.jpg",
                            "true",
                            "5.00°21.04\'0.00\" W",
                            "36.00°7.08\'0.00\" N",
                            "-5.35",
                            "36.11666666666667",
                            "27 Jan 2020 12:50:42",
                            "27 Jan 2020 11:50:41",
                            "27 Jan 2020 11:50:41",
                            "20200127_115041",
                            "Green;Blue;Gibraltar;Europe;"});
                table5.AddRow(new string[] {
                            "CheckTheImageHasGPSCoridinates\\Internet",
                            "GPS3.jpg",
                            "true",
                            "5.00°21.04\'0.00\" W",
                            "36.00°7.08\'0.00\" N",
                            "-5.35",
                            "36.11666666666667",
                            "27 Jan 2020 12:50:42",
                            "27 Jan 2020 11:50:41",
                            "27 Jan 2020 11:50:41",
                            "20200127_115041",
                            "Gibraltar;Europe;"});
                table5.AddRow(new string[] {
                            "CheckTheImageHasGPSCoridinates\\Internet",
                            "GPS4.jpg",
                            "true",
                            "5.00°21.04\'0.00\" W",
                            "36.00°7.08\'0.00\" N",
                            "-5.35",
                            "36.11666666666667",
                            "27 Jan 2020 12:50:42",
                            "27 Jan 2020 11:50:41",
                            "27 Jan 2020 11:50:41",
                            "20200127_115041",
                            "Gibraltar;Europe;"});
                table5.AddRow(new string[] {
                            "CheckTheImageHasGPSCoridinates\\Internet",
                            "Good.jpg",
                            "true",
                            "",
                            "",
                            "",
                            "",
                            "10 Mar 2018 11:53:53",
                            "10 Mar 2018 11:53:53",
                            "",
                            "20180310_115353",
                            ""});
                table5.AddRow(new string[] {
                            "CheckTheImageHasGPSCoridinates\\Internet",
                            "Good2.jpg",
                            "true",
                            "",
                            "",
                            "",
                            "",
                            "10 Mar 2018 11:53:53",
                            "10 Mar 2018 11:53:53",
                            "",
                            "20180310_115353",
                            "Red;Orange;"});
                table5.AddRow(new string[] {
                            "CheckTheImageHasGPSCoridinates\\Internet",
                            "Bad.jpg",
                            "true",
                            "",
                            "",
                            "",
                            "",
                            "",
                            "",
                            "",
                            "",
                            ""});
                table5.AddRow(new string[] {
                            "CheckTheImageHasGPSCoridinates\\NoInternet",
                            "GPS.jpg",
                            "false",
                            "5.00°21.04\'0.00\" W",
                            "36.00°7.08\'0.00\" N",
                            "-5.35",
                            "36.11666666666667",
                            "27 Jan 2020 12:50:42",
                            "27 Jan 2020 11:50:41",
                            "27 Jan 2020 11:50:41",
                            "20200127_115041",
                            ""});
                table5.AddRow(new string[] {
                            "CheckTheImageHasGPSCoridinates\\NoInternet",
                            "Good.jpg",
                            "false",
                            "",
                            "",
                            "",
                            "",
                            "10 Mar 2018 11:53:53",
                            "10 Mar 2018 11:53:53",
                            "",
                            "20180310_115353",
                            ""});
                table5.AddRow(new string[] {
                            "CheckTheImageHasGPSCoridinates\\NoInternet",
                            "GPS2.jpg",
                            "false",
                            "5.00°21.04\'0.00\" W",
                            "36.00°7.08\'0.00\" N",
                            "-5.35",
                            "36.11666666666667",
                            "27 Jan 2020 12:50:42",
                            "27 Jan 2020 11:50:41",
                            "27 Jan 2020 11:50:41",
                            "20200127_115041",
                            "Green;Blue;"});
                table5.AddRow(new string[] {
                            "CheckTheImageHasGPSCoridinates\\NoInternet",
                            "Good2.jpg",
                            "false",
                            "",
                            "",
                            "",
                            "",
                            "10 Mar 2018 11:53:53",
                            "10 Mar 2018 11:53:53",
                            "",
                            "20180310_115353",
                            "Red;Orange;"});
                table5.AddRow(new string[] {
                            "CheckTheImageHasGPSCoridinates\\NoInternet",
                            "Bad.jpg",
                            "false",
                            "",
                            "",
                            "",
                            "",
                            "",
                            "",
                            "",
                            "",
                            ""});
#line 33
 testRunner.Then("the following files have the values in the ImageFile object", ((string)(null)), table5, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="GPSKeywords")]
        [Xunit.TraitAttribute("FeatureTitle", "ImageGPS")]
        [Xunit.TraitAttribute("Description", "GPSKeywords")]
        public virtual void GPSKeywords()
        {
            string[] tagsOfScenario = ((string[])(null));
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("GPSKeywords", null, ((string[])(null)));
#line 48
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 3
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                            "Source",
                            "TestFolder",
                            "HasInternet",
                            "TestFile",
                            "Longitude",
                            "Latitude",
                            "ImageCreatedOriginal",
                            "ImageTaken",
                            "GPSImageTaken",
                            "Keywords"});
                table6.AddRow(new string[] {
                            "JPG\\Good.jpg",
                            "GPSKeywords",
                            "true",
                            "aaaa.jpg",
                            "5.00°21.04\'0.00\" W",
                            "36.00°7.08\'0.00\" N",
                            "27 Jan 2020 09:50:42",
                            "27 Jan 2020 09:50:42",
                            "27 Jan 2020 11:50:41",
                            ""});
                table6.AddRow(new string[] {
                            "JPG\\Good.jpg",
                            "GPSKeywords",
                            "true",
                            "bbbb.jpg",
                            "5.00°21.04\'0.00\" W",
                            "36.00°7.08\'0.00\" N",
                            "27 Jan 2020 10:50:42",
                            "27 Jan 2020 10:50:42",
                            "27 Jan 2020 12:50:41",
                            "BlueBell;Tinkerbell;"});
                table6.AddRow(new string[] {
                            "JPG\\Good.jpg",
                            "GPSKeywords",
                            "true",
                            "cccc.jpg",
                            "4.00°8.00\'37.392\" W",
                            "50.00°7.21\'56.066\" N",
                            "27 Jan 2019 11:45:42",
                            "27 Jan 2019 11:45:42",
                            "27 Jan 2019 13:45:42",
                            ""});
                table6.AddRow(new string[] {
                            "JPG\\Good.jpg",
                            "GPSKeywords",
                            "true",
                            "dddd.jpg",
                            "4.00°8.00\'37.392\" W",
                            "50.00°7.21\'56.066\" N",
                            "27 Jan 2019 12:45:42",
                            "27 Jan 2019 12:45:42",
                            "27 Jan 2019 14:45:42",
                            "rain;snow;sun;"});
                table6.AddRow(new string[] {
                            "JPG\\Good.jpg",
                            "GPSKeywords",
                            "true",
                            "eeee.jpg",
                            "",
                            "",
                            "27 Jan 2020 16:50:41",
                            "27 Jan 2020 16:50:41",
                            "",
                            ""});
                table6.AddRow(new string[] {
                            "JPG\\Good.jpg",
                            "GPSKeywords",
                            "true",
                            "ffff.jpg",
                            "",
                            "",
                            "27 Jan 2020 17:50:41",
                            "27 Jan 2020 17:50:41",
                            "",
                            "rain;snow;sun;"});
                table6.AddRow(new string[] {
                            "JPG\\Good.jpg",
                            "GPSKeywords",
                            "true",
                            "gggg.jpg",
                            "",
                            "",
                            "27 Jan 2020 18:50:41",
                            "27 Jan 2020 18:50:41",
                            "",
                            ""});
                table6.AddRow(new string[] {
                            "JPG\\Good.jpg",
                            "GPSKeywords",
                            "true",
                            "hhhh.jpg",
                            "",
                            "",
                            "27 Jan 2020 19:50:41",
                            "27 Jan 2020 19:50:41",
                            "",
                            "BlueBell;Tinkerbell;"});
                table6.AddRow(new string[] {
                            "JPG\\Good.jpg",
                            "GPSKeywords",
                            "false",
                            "iiii.jpg",
                            "5.00°21.04\'0.00\" W",
                            "36.00°7.08\'0.00\" N",
                            "27 Jan 2020 09:50:42",
                            "27 Jan 2020 09:50:42",
                            "27 Jan 2020 11:50:41",
                            ""});
                table6.AddRow(new string[] {
                            "JPG\\Good.jpg",
                            "GPSKeywords",
                            "false",
                            "jjjj.jpg",
                            "5.00°21.04\'0.00\" W",
                            "36.00°7.08\'0.00\" N",
                            "27 Jan 2020 10:50:42",
                            "27 Jan 2020 10:50:42",
                            "27 Jan 2020 12:50:41",
                            "BlueBell;Tinkerbell;"});
                table6.AddRow(new string[] {
                            "JPG\\Good.jpg",
                            "GPSKeywords",
                            "false",
                            "kkkk.jpg",
                            "4.00°8.00\'37.392\" W",
                            "50.00°7.21\'56.066\" N",
                            "27 Jan 2019 11:45:42",
                            "27 Jan 2019 11:45:42",
                            "27 Jan 2019 13:45:42",
                            ""});
                table6.AddRow(new string[] {
                            "JPG\\Good.jpg",
                            "GPSKeywords",
                            "false",
                            "llll.jpg",
                            "4.00°8.00\'37.392\" W",
                            "50.00°7.21\'56.066\" N",
                            "27 Jan 2019 12:45:42",
                            "27 Jan 2019 12:45:42",
                            "27 Jan 2019 14:45:42",
                            "rain;snow;sun;"});
                table6.AddRow(new string[] {
                            "JPG\\Good.jpg",
                            "GPSKeywords",
                            "false",
                            "mmmm.jpg",
                            "",
                            "",
                            "27 Jan 2020 16:50:41",
                            "27 Jan 2020 16:50:41",
                            "",
                            ""});
                table6.AddRow(new string[] {
                            "JPG\\Good.jpg",
                            "GPSKeywords",
                            "false",
                            "nnnn.jpg",
                            "",
                            "",
                            "27 Jan 2020 17:50:41",
                            "27 Jan 2020 17:50:41",
                            "",
                            "rain;snow;sun;"});
                table6.AddRow(new string[] {
                            "JPG\\Good.jpg",
                            "GPSKeywords",
                            "false",
                            "oooo.jpg",
                            "",
                            "",
                            "27 Jan 2020 18:50:41",
                            "27 Jan 2020 18:50:41",
                            "",
                            ""});
                table6.AddRow(new string[] {
                            "JPG\\Good.jpg",
                            "GPSKeywords",
                            "false",
                            "pppp.jpg",
                            "",
                            "",
                            "27 Jan 2020 19:50:41",
                            "27 Jan 2020 19:50:41",
                            "",
                            "BlueBell;Tinkerbell;"});
                table6.AddRow(new string[] {
                            "JPG\\Good.jpg",
                            "GPSKeywords",
                            "true",
                            "qqqq.jpg",
                            "5.00°21.04\'0.00\" W",
                            "36.00°7.08\'0.00\" N",
                            "27 Jan 2020 09:50:42",
                            "27 Jan 2020 09:50:42",
                            "27 Jan 2020 11:50:41",
                            "Gibraltar;"});
                table6.AddRow(new string[] {
                            "JPG\\Good.jpg",
                            "GPSKeywords",
                            "true",
                            "rrrr.jpg",
                            "5.00°21.04\'0.00\" W",
                            "36.00°7.08\'0.00\" N",
                            "27 Jan 2020 09:50:42",
                            "27 Jan 2020 09:50:42",
                            "27 Jan 2020 11:50:41",
                            "Gibraltar;Europe;"});
                table6.AddRow(new string[] {
                            "JPG\\Good.jpg",
                            "GPSKeywords",
                            "true",
                            "ssss.jpg",
                            "4.00°41.00\'59.279\" W",
                            "51.00°41.00\'39.24\" N",
                            "27 Jan 2020 09:50:42",
                            "27 Jan 2020 09:50:42",
                            "27 Jan 2020 11:50:41",
                            ""});
                table6.AddRow(new string[] {
                            "JPG\\Good.jpg",
                            "GPSKeywords",
                            "true",
                            "tttt.jpg",
                            "12.00°30.00\'21.763\" E",
                            "55.00°52.00\'25.54\" N",
                            "27 Jan 2020 09:50:42",
                            "27 Jan 2020 09:50:42",
                            "27 Jan 2020 11:50:41",
                            ""});
                table6.AddRow(new string[] {
                            "JPG\\Good.jpg",
                            "GPSKeywords",
                            "true",
                            "uuuu.jpg",
                            "6.00°42.00\'37.335\" E",
                            "45.00°48.00\'15.45\" N",
                            "27 Jan 2020 09:50:42",
                            "27 Jan 2020 09:50:42",
                            "27 Jan 2020 11:50:41",
                            ""});
                table6.AddRow(new string[] {
                            "JPG\\Good.jpg",
                            "GPSKeywords",
                            "true",
                            "vvvv.jpg",
                            "9.00°52.00\'4.4\" E",
                            "53.00°33.00\'38.652\" N",
                            "27 Jan 2020 09:50:42",
                            "27 Jan 2020 09:50:42",
                            "27 Jan 2020 11:50:41",
                            ""});
#line 49
 testRunner.Given("I create image objects with the following properties", ((string)(null)), table6, "Given ");
#line hidden
                TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                            "TestFile",
                            "Longitude",
                            "Latitude",
                            "DegreesLongitude",
                            "DegreesLatitude",
                            "ImageCreatedOriginal",
                            "ImageTaken",
                            "GPSImageTaken",
                            "DestinationFileName",
                            "KeyWords"});
                table7.AddRow(new string[] {
                            "aaaa.jpg",
                            "5.00°21.04\'0.00\" W",
                            "36.00°7.08\'0.00\" N",
                            "-5.35",
                            "36.11666666666667",
                            "27 Jan 2020 09:50:42",
                            "27 Jan 2020 09:50:42",
                            "27 Jan 2020 11:50:41",
                            "20200127_115041",
                            "Gibraltar;Europe;"});
                table7.AddRow(new string[] {
                            "bbbb.jpg",
                            "5.00°21.04\'0.00\" W",
                            "36.00°7.08\'0.00\" N",
                            "-5.35",
                            "36.11666666666667",
                            "27 Jan 2020 10:50:42",
                            "27 Jan 2020 10:50:42",
                            "27 Jan 2020 12:50:41",
                            "20200127_125041",
                            "BlueBell;Tinkerbell;Gibraltar;Europe;"});
                table7.AddRow(new string[] {
                            "cccc.jpg",
                            "4.00°8.00\'37.392\" W",
                            "50.00°7.21\'56.066\" N",
                            "-4.14372",
                            "50.132240555555555",
                            "27 Jan 2019 11:45:42",
                            "27 Jan 2019 11:45:42",
                            "27 Jan 2019 13:45:42",
                            "20190127_134542",
                            ""});
                table7.AddRow(new string[] {
                            "dddd.jpg",
                            "4.00°8.00\'37.392\" W",
                            "50.00°7.21\'56.066\" N",
                            "-4.14372",
                            "50.132240555555555",
                            "27 Jan 2019 12:45:42",
                            "27 Jan 2019 12:45:42",
                            "27 Jan 2019 14:45:42",
                            "20190127_144542",
                            "rain;snow;sun;"});
                table7.AddRow(new string[] {
                            "eeee.jpg",
                            "",
                            "",
                            "",
                            "",
                            "27 Jan 2020 16:50:41",
                            "27 Jan 2020 16:50:41",
                            "",
                            "20200127_165041",
                            ""});
                table7.AddRow(new string[] {
                            "ffff.jpg",
                            "",
                            "",
                            "",
                            "",
                            "27 Jan 2020 17:50:41",
                            "27 Jan 2020 17:50:41",
                            "",
                            "20200127_175041",
                            "rain;snow;sun;"});
                table7.AddRow(new string[] {
                            "gggg.jpg",
                            "",
                            "",
                            "",
                            "",
                            "27 Jan 2020 18:50:41",
                            "27 Jan 2020 18:50:41",
                            "",
                            "20200127_185041",
                            ""});
                table7.AddRow(new string[] {
                            "hhhh.jpg",
                            "",
                            "",
                            "",
                            "",
                            "27 Jan 2020 19:50:41",
                            "27 Jan 2020 19:50:41",
                            "",
                            "20200127_195041",
                            "BlueBell;Tinkerbell;"});
                table7.AddRow(new string[] {
                            "iiii.jpg",
                            "5.00°21.04\'0.00\" W",
                            "36.00°7.08\'0.00\" N",
                            "-5.35",
                            "36.11666666666667",
                            "27 Jan 2020 09:50:42",
                            "27 Jan 2020 09:50:42",
                            "27 Jan 2020 11:50:41",
                            "20200127_115041",
                            ""});
                table7.AddRow(new string[] {
                            "jjjj.jpg",
                            "5.00°21.04\'0.00\" W",
                            "36.00°7.08\'0.00\" N",
                            "-5.35",
                            "36.11666666666667",
                            "27 Jan 2020 10:50:42",
                            "27 Jan 2020 10:50:42",
                            "27 Jan 2020 12:50:41",
                            "20200127_125041",
                            "BlueBell;Tinkerbell;"});
                table7.AddRow(new string[] {
                            "kkkk.jpg",
                            "4.00°8.00\'37.392\" W",
                            "50.00°7.21\'56.066\" N",
                            "-4.14372",
                            "50.132240555555555",
                            "27 Jan 2019 11:45:42",
                            "27 Jan 2019 11:45:42",
                            "27 Jan 2019 13:45:42",
                            "20190127_134542",
                            ""});
                table7.AddRow(new string[] {
                            "llll.jpg",
                            "4.00°8.00\'37.392\" W",
                            "50.00°7.21\'56.066\" N",
                            "-4.14372",
                            "50.132240555555555",
                            "27 Jan 2019 12:45:42",
                            "27 Jan 2019 12:45:42",
                            "27 Jan 2019 14:45:42",
                            "20190127_144542",
                            "rain;snow;sun;"});
                table7.AddRow(new string[] {
                            "mmmm.jpg",
                            "",
                            "",
                            "",
                            "",
                            "27 Jan 2020 16:50:41",
                            "27 Jan 2020 16:50:41",
                            "",
                            "20200127_165041",
                            ""});
                table7.AddRow(new string[] {
                            "nnnn.jpg",
                            "",
                            "",
                            "",
                            "",
                            "27 Jan 2020 17:50:41",
                            "27 Jan 2020 17:50:41",
                            "",
                            "20200127_175041",
                            "rain;snow;sun;"});
                table7.AddRow(new string[] {
                            "oooo.jpg",
                            "",
                            "",
                            "",
                            "",
                            "27 Jan 2020 18:50:41",
                            "27 Jan 2020 18:50:41",
                            "",
                            "20200127_185041",
                            ""});
                table7.AddRow(new string[] {
                            "pppp.jpg",
                            "",
                            "",
                            "",
                            "",
                            "27 Jan 2020 19:50:41",
                            "27 Jan 2020 19:50:41",
                            "",
                            "20200127_195041",
                            "BlueBell;Tinkerbell;"});
                table7.AddRow(new string[] {
                            "qqqq.jpg",
                            "5.00°21.04\'0.00\" W",
                            "36.00°7.08\'0.00\" N",
                            "-5.35",
                            "36.11666666666667",
                            "27 Jan 2020 09:50:42",
                            "27 Jan 2020 09:50:42",
                            "27 Jan 2020 11:50:41",
                            "20200127_115041",
                            "Gibraltar;Europe;"});
                table7.AddRow(new string[] {
                            "rrrr.jpg",
                            "5.00°21.04\'0.00\" W",
                            "36.00°7.08\'0.00\" N",
                            "-5.35",
                            "36.11666666666667",
                            "27 Jan 2020 09:50:42",
                            "27 Jan 2020 09:50:42",
                            "27 Jan 2020 11:50:41",
                            "20200127_115041",
                            "Gibraltar;Europe;"});
                table7.AddRow(new string[] {
                            "ssss.jpg",
                            "4.00°41.00\'59.279\" W",
                            "51.00°41.00\'39.24\" N",
                            "-4.699799722222222",
                            "51.69423333333333",
                            "27 Jan 2020 09:50:42",
                            "27 Jan 2020 09:50:42",
                            "27 Jan 2020 11:50:41",
                            "20200127_115041",
                            "United Kingdom;Europe;Wales;Pembrokeshire;"});
                table7.AddRow(new string[] {
                            "tttt.jpg",
                            "12.00°30.00\'21.763\" E",
                            "55.00°52.00\'25.54\" N",
                            "12.506045277777778",
                            "55.873761111111115",
                            "27 Jan 2020 09:50:42",
                            "27 Jan 2020 09:50:42",
                            "27 Jan 2020 11:50:41",
                            "20200127_115041",
                            "Denmark;Europe;Hørsholm;"});
                table7.AddRow(new string[] {
                            "uuuu.jpg",
                            "6.00°42.00\'37.335\" E",
                            "45.00°48.00\'15.45\" N",
                            "6.710370833333333",
                            "45.804291666666664",
                            "27 Jan 2020 09:50:42",
                            "27 Jan 2020 09:50:42",
                            "27 Jan 2020 11:50:41",
                            "20200127_115041",
                            "France;Europe;Auvergne-Rhone-Alpes;Haute-Savoie;"});
                table7.AddRow(new string[] {
                            "vvvv.jpg",
                            "9.00°52.00\'4.4\" E",
                            "53.00°33.00\'38.652\" N",
                            "9.867888888888888",
                            "53.56073666666666",
                            "27 Jan 2020 09:50:42",
                            "27 Jan 2020 09:50:42",
                            "27 Jan 2020 11:50:41",
                            "20200127_115041",
                            "Germany;Europe;Hamburg;"});
#line 75
 testRunner.Then("the image object list has following values", ((string)(null)), table7, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.1.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                ImageGPSFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                ImageGPSFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
